[package]
version = "0.1.0"
edition = "2021"
name = "tracing-profile"
description = "A span based profiler, utilizing the tracing crate"
keywords = ["metrics", "profiling", "tracing"]
license-file = "LICENSE.txt"
readme = "README.md"
repository = "https://gitlab.com/UlvetannaOSS/tracing-profile"

[dependencies]
once_cell = "1.19.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[features]
panic = []
