[package]
name = "perfetto-sys"
version = "0.4.0"
edition = "2021"

[dependencies]

[build-dependencies]
cmake = "0.1"
convert_case = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
